builds:
  - binary: osiris
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: osiris
    homepage: "https://github.com/Voldemat/osiris"
    tap:
      owner: Voldemat
      name: homebrew-voldemat
    commit_author:
      name: Vladimir
      email: vladimirdev635@gmail.com

checksum:
  name_template: 'checksums.txt'
